name: DB Backup
on:
  schedule:
    - cron: '0 21 * * *'  # 2:30am IST daily
  workflow_dispatch:       # allows manual trigger too

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Install pg tools
        run: sudo apt-get install -y postgresql-client

      - name: Dump and restore
        env:
          SUPABASE_DB_URL: ${{secrets.SUPABASE_DB_URL}}
          NEON_DB_URL: ${{secrets.NEON_DB_URL}}
        run: |
          pg_dump "$SUPABASE_DB_URL" \ --no-owner --no-acl \ -Fc \ --schema=public \ --section=pre-data \ --section=data \ --section=post-data \ -f backup.dump
          pg_restore --clean --if-exists --no-owner --no-acl -d "$NEON_DB_URL" backup.dump